//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace P02MVCAjax.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Student
    {
        public int Id { get; set; }
        public Nullable<int> CId { get; set; }
        //[StringLength(4, ErrorMessage = "姓名不能超过四个")]
        //[Required(ErrorMessage = "<script>alert('姓名必填')</script>")]
        //[Range(typeof(String),"a","z")]
        //[Birthday(ErrorMessage = "年龄必须 18 到 65")]
        //[Range(typeof(DateTime), "1/2/2004", "3/4/2020",
        //ErrorMessage = "Value for {0} must be between {1} and {2}")]//超过
        //[RegularExpression("^[a-z]+$")]
        //[Compare("CId")]
        [Remote("ExitName", "Student", ErrorMessage = "姓名已存在")]
        public string Name { get; set; }
        public string Gender { get; set; }
        public bool IsDel { get; set; }
        public System.DateTime AddTime { get; set; }

        public virtual Class Class { get; set; }
    }
}
