//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFirstMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int Id { get; set; }
        public Nullable<int> CId { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public bool IsDel { get; set; }
        public System.DateTime AddTime { get; set; }
    
        public virtual Class Class { get; set; }
    }
}
